name: Actualización de cliente

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: "Nombre del cliente recurrente"
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar actualización
        run: echo "usuario1-dev y usuario2-op: se ha actualizado el cliente '${{ github.event.inputs.cliente }}'"
