name: Consulta de cliente

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: "Cliente consultado"
        required: true
        default: "ClienteEjemplo"

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje de consulta
        run: |
          echo "usuario1-dev y usuario2-op: se ha consultado el cliente '${{ github.event.inputs.cliente }}'"
