name: Creación de nuevo cliente

on:
  workflow_dispatch:
    inputs:
      cliente:
        description: "Nombre del nuevo cliente"
        required: true
        default: "ClienteEjemplo"

jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje de creación
        run: |
          echo "usuario1-dev y usuario2-op: se ha creado el cliente '${{ github.event.inputs.cliente }}'"
